InstrumentDataManagement/urls.py
'''
Created on 14.09.2016

@author: Moustafa Shama
'''
from django.conf.urls import url

from . import views

app_name = 'InstrumentDataManagement'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^newInstrument/$', views.newInstrument, name='newInstrument'),
    url(r'^deleteInstrument/(?P<instrument_id>[0-9]+)/$', views.deleteInstrument, name='deleteInstrument'),
    url(r'^viewInstrument/$', views.viewInstrument, name='viewInstrument'),
    url(r'^viewInstrument/(?P<instrument_id>[0-9]+)/$', views.viewInstrument, name='viewInstrument'),
    url(r'^viewInstrument/(?P<instrument_id>[0-9]+)/(?P<msg>(.*))/$', views.viewInstrument, name='viewInstrument'),
    url(r'^searchInstruments/$', views.searchInstruments, name='searchInstruments'),
    url(r'^addInstrumentSynonym/$', views.addInstrumentSynonym, name='addInstrumentSynonym'),
    url(r'^deltInstrumentSynonym/(?P<synonym_id>[0-9]+)/$', views.deltInstrumentSynonym, name='deltInstrumentSynonym'),
    url(r'^viewAssetClasses/$', views.viewAssetClasses, name='viewAssetClasses'),
    url(r'^viewAssetClasses/(?P<assetclass_id>[0-9]*)/$', views.viewAssetClasses, name='viewAssetClasses'),
    url(r'^newAssetClass/$', views.newAssetClass, name='newAssetClass'),
    url(r'^addInstrumentAssetClass/(?P<assetclass_id>[0-9]+)/$', views.addInstrumentAssetClass, name='addInstrumentAssetClass'),
    url(r'^deltInstrumentAssetClass/(?P<assetclass_id>[0-9]+)/$', views.deltInstrumentAssetClass, name='deltInstrumentAssetClass'),
]

QuantServer/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('home.urls')),
    url(r'^InstrumentDataManagement/', include('InstrumentDataManagement.urls')),
    url(r'^MarketDataManagement/', include('MarketDataManagement.urls')),
    url(r'^RiskModelManagement/', include('RiskModelManagement.urls')),
    url(r'^PortfolioPositionManagement/', include('PortfolioPositionManagement.urls')),
    url(r'^RiskModelManagement/', include('RiskModelManagement.urls')),
    url(r'^UserManagement/', include('UserManagement.urls')),
    url(r'^ManualUpload/', include('ManualUpload.urls')),
    url(r'^Reporting/', include('Reporting.urls')),
]

home/urls.py
'''
Created on 22.06.2016

@author: Moustafa Shama
'''

from django.conf.urls import url

from . import views


app_name = 'home'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^checkLogin/$', views.checkLogin, name='checkLogin'),
]

InstrumentDataManagement/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.db import IntegrityError

# build in libraries
from datetime import datetime

# models import
from .models import Instrument, Instrumentsynonym, \
    AssetClass, AssetClass_Instrument

# forms import
from .forms import newMarketDataTypeForm,newMarketForm,newInstrumentForm,\
    newCountryForm, newCurrencyForm, newAssetClassForm, instrumentAssetClassMapping, newInstrumentSynonymForm


from data_saving.saving_functions import new_instrument
from MarketDataManagement.models import MarketData_Equity_DataStream_C,\
    MarketData_Equity_Bloomberg_C, MarketData_Equity_C,\
    MarketData_Fixed_Income_DataStream_C, MarketData_Fixed_Income_Bloomberg_C,\
    MarketData_InterestRate_DataStream_C, MarketData_InterestRate_Bloomberg_C,\
    MarketData_Derivative_DataStream_C, MarketData_Derivative_Bloomberg_C,\
    MarketData_Index_DataStream_C, MarketData_Index_Bloomberg_C,\
    MarketData_Derivative_C, MarketData_InterestRate_C,\
    MarketData_Fixed_Income_C, MarketData_Index_C
from InstrumentDataManagement.models import Codification
from InstrumentDataManagement.forms import instrumentSearchForm

# Create your views here.

def index(request):
    context = {'message': 'this is the data management home'}
    return render(request, 'InstrumentDataManagement/index.html', context)

def searchInstruments(request):
    if request.method == 'GET':
        searchForm = instrumentSearchForm()
        context = {
                   'searchForm': searchForm
                   }
        return render(request, 'InstrumentDataManagement/searchInstruments.html', context)
    elif request.method == 'POST':
        searchForm = instrumentSearchForm(request.POST)
        if searchForm.is_valid():
            instrumentCodes = searchForm.cleaned_data['names'].split('\r\n')
            if searchForm.cleaned_data['source'] == 'DS':
                ticker_type = 'DS_Ticker'
            elif searchForm.cleaned_data['source'] == 'BBG':
                ticker_type = 'BBG_Ticker'
            elif searchForm.cleaned_data['source'] == 'ISIN':
                ticker_type = 'ISIN'
                
            instruments = Instrument.objects.filter(instrumentsynonym__code_c__in=instrumentCodes, instrumentsynonym__codification=Codification.objects.get(name_c=ticker_type))
            
            if searchForm.cleaned_data['marketdatatype']:
                instruments = [i for i in instruments if i.marketdatatype == searchForm.cleaned_data['marketdatatype']]
                
            if searchForm.cleaned_data['market']:
                instruments = [i for i in instruments if i.marketdatatype == searchForm.cleaned_data['market']]
        
        else:
            instruments = []
        
        context = {
                   'instruments': instruments,
                   }
        return render(request, 'InstrumentDataManagement/viewInstruments.html', context)

def addInstrumentSynonym(request):
    form = newInstrumentSynonymForm(request.POST)
    if form.is_valid():
        try:
            instrument = Instrument.objects.get(pk=form.cleaned_data['instrument'])
            Instrumentsynonym(instrument=instrument,
                              codification=form.cleaned_data['codification'],
                              code_c = form.cleaned_data['code_c'],
                              validity_d = datetime.now().date()).save()
        except IntegrityError:
            msg = "Cannon Insert this Synonym. Either it already exists or the Instrument has already a Synonym with the same type"
        return redirect('InstrumentDataManagement:viewInstrument',instrument_id=instrument.id, msg=msg)
    return redirect('InstrumentDataManagement:viewInstrument')

def deltInstrumentSynonym(request, synonym_id):
    synonym = Instrumentsynonym.objects.get(pk=synonym_id)
    instrument_id = synonym.instrument.id
    synonym.delete()
    
    return redirect('InstrumentDataManagement:viewInstrument', instrument_id=instrument_id, )

def deleteInstrument(request, instrument_id=None):
    if instrument_id != None:
        instrument = Instrument.objects.get(pk=instrument_id)
        
        instrument.delete()
        
        return redirect('InstrumentDataManagement:viewInstrument')
    

def viewInstrument(request, instrument_id='', msg=None):
    if request.method == 'POST':
        pass
    elif request.method == 'GET':
        if instrument_id != '':
            instrumentSynonyms = Instrumentsynonym.objects.filter(instrument_id=instrument_id).order_by('codification')
            instrument = Instrument.objects.get(id=instrument_id)
            synonymForm = newInstrumentSynonymForm(initial={'instrument': instrument_id})
            context = {
                       'instrumentSynonyms': instrumentSynonyms,
                       'instrument': instrument,
                       'synonymForm': synonymForm,
                       'errorMessages': msg,
                       }
            return render(request, 'InstrumentDataManagement/viewInstrumentDetails.html', context)
        else:
            instruments = Instrument.objects.all()
        
            context = {
                       'instruments': instruments,
                       }
            return render(request, 'InstrumentDataManagement/viewInstruments.html', context)
        
def newInstrument(request):
    # check which type of post was executed in the html
    if request.method == 'POST':
        if 'newInstrument' in request.POST:
            insertInstruments(request)                    
        elif 'newMarketDataType' in request.POST:
            newMarketDataType(request)
        elif 'newMarket' in request.POST:
            newMarket(request)
        elif 'newCountry' in request.POST:
            newCountry(request)
        elif 'newCurrency' in request.POST:
            newCurrency(request)
    instrumentForm = newInstrumentForm()
    marketDataTypeForm = newMarketDataTypeForm()
    marketForm = newMarketForm()
    countryForm = newCountryForm()
    currencyForm = newCurrencyForm()
    
    context = {
               'message': 'this is the data management home',
               'instrumentForm': instrumentForm,
               'marketDataTypeForm': marketDataTypeForm,
               'marketForm': marketForm,
               'countryForm': countryForm,
               'currencyForm': currencyForm,
               }
    return render(request, 'InstrumentDataManagement/newInstrument.html', context)

def insertInstruments(request):
    """
    when a new instrument is inserted from the UI we don't check if it already exists
    we try to read the meta data for it and insert it as a new instrument
    """
    
    form = newInstrumentForm(request.POST)
    if form.is_valid():
        instrumentCodes = form.cleaned_data['names'].split('\r\n')
        market = form.cleaned_data['market'].iso_code_c if form.cleaned_data['market'] != None else None
        for instrumentCode in instrumentCodes:
            new_instrument(instrument_ticker=instrumentCode, 
                           ticker_type=form.cleaned_data['source'], 
                           market_data_type=form.cleaned_data['marketdatatype'].name_c, 
                           currency=form.cleaned_data['currency'], 
                           underlying_curreny=form.cleaned_data['underlyingcurrency'], 
                           market=form.cleaned_data['market'],
                           country=form.cleaned_data['country'],
                           risk_country=form.cleaned_data['risk_country'])

def newMarketDataType(request):
    form = newMarketDataTypeForm(request.POST)
    if not form.save():
        return False
        
def newMarket(request):
    form = newMarketForm(request.POST)
    if not form.save():
        return False
        
def newCountry(request):
    form = newCountryForm(request.POST)
    if not form.save():
        return False

def newCurrency(request):
    form = newCurrencyForm(request.POST)
    if not form.save():
        return False
        
def viewAssetClasses(request, assetclass_id=''):
    if request.method == 'GET':
        if assetclass_id != '':
            asset_class = AssetClass.objects.get(pk=assetclass_id)
            mappings = AssetClass_Instrument.objects.filter(assetclass=asset_class)
            mappingForm = instrumentAssetClassMapping()
            context = {                       
                       'asset_class': asset_class,
                       'mappings': mappings,
                       'mappingForm': mappingForm,
                       }
            return render(request, 'InstrumentDataManagement/viewAssetClassDetails.html', context)
        else:
            asset_classes = AssetClass.objects.all().order_by('parent_assetclass')
            assetClassForm = newAssetClassForm()
            context = {
                       'asset_classes': asset_classes,
                       'assetClassForm': assetClassForm,
                       }
            return render(request, 'InstrumentDataManagement/viewAssetClasses.html', context)
        
def newAssetClass(request):
    if request.method == 'POST':
        form = newAssetClassForm(request.POST)
        if form.is_valid():
            asset_class = AssetClass(**form.cleaned_data)
            if asset_class.parent_assetclass is None:
                asset_class.level_n = 0
            else:
                asset_class.level_n = asset_class.parent_assetclass.level_n + 1
            asset_class.save()
            return redirect('InstrumentDataManagement:viewAssetClasses')
        else:
            return HttpResponse('Error')

def deltInstrumentAssetClass(request, assetclass_id=''):
    if request.method == 'POST':
        mappings_ids = request.POST.getlist('mappings_ids')
        mapings = AssetClass_Instrument.objects.filter(pk__in=mappings_ids).delete()

InstrumentDataManagement/templates/InstrumentDataManagement/addInstrumentAssetClass.html
<div id="instrument-asset-class-overlay" class="overlay-form-large">
	<div>
		<h3><label> Enter New Asset Class</label></h3>
		<form action="{% url 'InstrumentDataManagement:addInstrumentAssetClass' asset_class.id%}" method="post">
		    {% csrf_token %}
		    {{ mappingForm.as_p }}
		    <br /> 
		    <input name="newMarket" type="submit" value="Add" class="submit-button"/>
		</form>
	<a href='#' onclick='overlayClick("instrument-asset-class-overlay")'>close</a>
	</div>
</div>

InstrumentDataManagement/templates/InstrumentDataManagement/addInstrumentSynynom.html
<div id="instrument-synonym-overlay" class="overlay-form">
	<div>
		<h3><label> Add instrument synonym</label></h3>
		<form action="{% url 'InstrumentDataManagement:addInstrumentSynonym'%}" method="post">
		    {% csrf_token %}
		    {{ synonymForm.as_p }}
		    <br /> 
		    <input name="addInstrumentSynonym" type="submit" value="Submit" class="submit-button"/>
		</form>
	<a href='#' onclick='overlayClick("instrument-synonym-overlay")'>close</a>
	</div>
</div>

InstrumentDataManagement/templates/InstrumentDataManagement/confirmDeleteInstrument.html
<div id="confirm-delete-overlay" class="overlay-form">
	<div>
		<h3><label> Are you sure you want to delete this instrument?</label></h3>
		<form action="{% url 'InstrumentDataManagement:deleteInstrument' instrument.id%}" method="POST">
		    {% csrf_token %}
		    <br /> 
		    <input name="deleteInstrument" type="submit" value="Submit" class="submit-button"/>
		</form>
	<a href='#' onclick='overlayClick("confirm-delete-overlay")'>close</a>
	</div>
</div>

InstrumentDataManagement/templates/InstrumentDataManagement/includes.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'InstrumentDataManagement/css/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'MarketDataManagement/css/filtergrid.css' %}" />
<script type="text/javascript"  src="{% static 'InstrumentDataManagement/js/jquery.min.js' %}"></script>
<script type="text/javascript"  src="{% static 'InstrumentDataManagement/js/scripts.js' %}"></script>
<script type="text/javascript" src="{% static 'InstrumentDataManagement/js/actb.js' %}"></script><!-- External script -->
<script type="text/javascript" src="{% static 'InstrumentDataManagement/js/tablefilter.js' %}"></script> <!-- Credit: Max Guglielmi -->

InstrumentDataManagement/templates/InstrumentDataManagement/newAssetClass.html
<div id="asset-class-overlay" class="overlay-form">
	<div>
		<h3><label> Enter New Asset Class</label></h3>
		<form action="{% url 'InstrumentDataManagement:newAssetClass'%}" method="post">
		    {% csrf_token %}
		    {{ assetClassForm.as_p }}
		    <br /> 
		    <input name="newAssetClass" type="submit" value="Add" class="submit-button"/>
		</form>
	<a href='#' onclick='overlayClick("asset-class-overlay")'>close</a>
	</div>
</div>

InstrumentDataManagement/templates/InstrumentDataManagement/newCountry.html
<div id="country-overlay" class="overlay-form">
	<div>
		<h3><label> Enter New Country:</label></h3>
		<form action="{% url 'InstrumentDataManagement:newInstrument'%}" method="post">
		    {% csrf_token %}
		    {{ countryForm.as_p }}
		    <br /> 
		    <input name="newCountry" type="submit" value="Submit" class="submit-button"/>
		</form>
	<a href='#' onclick='overlayClick("country-overlay")'>close</a>
	</div>
</div>

InstrumentDataManagement/templates/InstrumentDataManagement/newCurrency.html
<div id="currency-overlay" class="overlay-form">
	<div>
		<h3><label> Enter New currency:</label></h3>
		<form action="{% url 'InstrumentDataManagement:newInstrument'%}" method="post">
		    {% csrf_token %}
		    {{ currencyForm.as_p }}
		    <br /> 
		    <input name="newCurrency" type="submit" value="Submit" class="submit-button"/>
		</form>
	<a href='#' onclick='overlayClick("currency-overlay")'>close</a>
	</div>
</div>

InstrumentDataManagement/templates/InstrumentDataManagement/newMarket.html
<div id="market-overlay" class="overlay-form">
	<div>
		<h3><label> Enter New Market</label></h3>
		<form action="{% url 'InstrumentDataManagement:newInstrument'%}" method="post">
		    {% csrf_token %}
		    {{ marketForm.as_p }}
		    <br /> 
		    <input name="newMarket" type="submit" value="Submit" class="submit-button"/>
		</form>
	<a href='#' onclick='overlayClick("market-overlay")'>close</a>
	</div>
</div>

InstrumentDataManagement/templates/InstrumentDataManagement/newMarketDataType.html
<div id="marketdatatype-overlay" class="overlay-form">
	<div>
		<h3><label> Enter New Market Data Type:</label></h3>
		<form action="{% url 'InstrumentDataManagement:newInstrument'%}" method="post">
		    {% csrf_token %}
		    {{ marketDataTypeForm.as_p }}
		    <br /> 
		    <input name="newMarketDataType" type="submit" value="Submit" class="submit-button"/>
		</form>
	<a href='#' onclick='overlayClick("marketdatatype-overlay")'>close</a>
	</div>
</div>

InstrumentDataManagement/templates/InstrumentDataManagement/searchInstruments.html
{% extends 'home/base.html' %}
{% block body_block %}
	{% include 'InstrumentDataManagement/includes.html' %}
	
	<form action="{% url 'InstrumentDataManagement:searchInstruments'%}" method="POST">
	    {% csrf_token %}
		<table style="width: 50%;margin-left: auto;margin-right: auto;text-align:left">
	    	{{ searchForm.as_table }}
		</table>
	    <input name="newInstrument" type="submit" value="Search" class="submit-button"/>
	</form>
{% endblock %}

InstrumentDataManagement/templates/InstrumentDataManagement/viewAssetClassDetails.html
{% extends 'home/base.html' %}
{% block body_block %}
	{% include 'InstrumentDataManagement/includes.html' %}
	{% include 'InstrumentDataManagement/newAssetClass.html' %}
	{% include 'InstrumentDataManagement/addInstrumentAssetClass.html' %}
	
	<h2>Asset class details</h2>
	<table style="width: 30%;margin-left: auto;margin-right: auto;text-align:center">
		<tr>
			<th>Name:</th>
			<td>{{ asset_class.name_c }}</td>
		</tr>
		<tr>
			<th>Denomination:</th>
			<td>{{ asset_class.denomination_c }}</td>
		</tr>
		<tr>
			<th>Level:</th>
			<td>{{ asset_class.level_n }}</td>
		</tr>
		<tr>
			<th>Parent:</th>
			<td><a href="{% url 'InstrumentDataManagement:viewAssetClasses' asset_class.parent_assetclass.id %}">{{ asset_class.parent_assetclass.name_c | default_if_none:"" }}</a></td>
		</tr>
	</table>
	<hr>
	<form action="{% url 'InstrumentDataManagement:deltInstrumentAssetClass' asset_class.id%}" method="post">
		{% csrf_token %}
		<table style="width: 60%;margin-left: auto;margin-right: auto;text-align:left" id="list-table">
			<tr>
				<th>Select</th>
				<th>Instrument</th>
				<th>Mandate</th>
			</tr>
			{% for mapping in mappings %}
			<tr>
				<td><input type="checkbox" name="mappings_ids" value="{{ mapping.id }}"></td>
				<td>{{ mapping.instrument.name_c }}</td>
				<td>{{ mapping.mandate.name_c | add:" - " | add:mapping.mandate.portfolio.name_c }}</td>
			</tr>
			{% endfor %}
		</table>
		
		<script language="javascript" type="text/javascript">
			var filter_config = 	{
					paging: true,
					paging_length: 10,
					rows_counter: true,
					btn_reset: true,
				};
			setFilterGrid("list-table",filter_config);
		</script>
		<br><br>
		<a href="#" onclick="overlayClick('instrument-asset-class-overlay')" class="button-link">Add instrument(s) to asset class</a>
		<br><br>
		<input type="submit" value="Delete selected" class="submit-button">
		<br><br>
		<a href="{% url 'InstrumentDataManagement:viewAssetClasses' %}" class="button-link">Back</a>
	</form>
{% endblock %}

InstrumentDataManagement/templates/InstrumentDataManagement/viewAssetClasses.html
{% extends 'home/base.html' %}
{% block body_block %}
	{% include 'InstrumentDataManagement/includes.html' %}
	{% include 'InstrumentDataManagement/newAssetClass.html' %}
	
	<table style="width: 60%;margin-left: auto;margin-right: auto;text-align:left" id="list-table">
		<tr>
			<th>Name</th>
			<th>Denomination</th>
			<th>Level</th>
			<th>Parent</th>
		</tr>
		{% for asset_class in asset_classes %}
		<tr>
			<td><a href="{% url 'InstrumentDataManagement:viewAssetClasses' asset_class.id %}">{{ asset_class.name_c }}</a></td>
			<td>{{ asset_class.denomination_c | default_if_none:"" }}</td>
			<td>{{ asset_class.level_n | default_if_none:"" }}</td>
			<td>{{ asset_class.parent_assetclass.name_c | default_if_none:"" }}</td>
		</tr>
		{% endfor %}
	</table>
	
	<script language="javascript" type="text/javascript">
		var filter_config = 	{
				paging: true,
				paging_length: 10,
				rows_counter: true,
				btn_reset: true,
			};
		setFilterGrid("list-table",filter_config);
	</script>
	<br><br>
	<a href="#" onclick="overlayClick('asset-class-overlay')" class="button-link">New asset class</a>
{% endblock %}

InstrumentDataManagement/templates/InstrumentDataManagement/viewInstrument.html
{% extends 'home/base.html' %}
{% block body_block %}
	{% include 'InstrumentDataManagement/includes.html' %}
	
	<table style="width: 90%;margin-left: auto;margin-right: auto;text-align:left" id="list-table">
		<tr>
			<th>Name</th>
			<th>Market Data Type</th>
			<th>Market</th>
			<th>Country</th>
			<th>Currency</th>
			<th>Underlying Currency</th>
			<th>Risk Country</th>
		</tr>
		{% for instrument in instruments %}
		<tr>
			<td><a href="{% url 'InstrumentDataManagement:viewInstrument' instrument.id %}">{{ instrument.name_c }}</a></td>
			<td>{{ instrument.marketdatatype.name_c }}</td>
			<td>{{ instrument.market.name_c  | default_if_none:""}}</td>
			<td>{{ instrument.country.name_c  | default_if_none:""}}</td>
			<td>{{ instrument.currency.name_c | default_if_none:"" }}</td>
			<td>{{ instrument.underlying_currency.name_c | default_if_none:"" }}</td>
			<td>{{ instrument.risk_country.name_c | default_if_none:"" }}</td>
		</tr>
		{% endfor %}
	</table>
	
	<script language="javascript" type="text/javascript">
		var filter_config = 	{
				paging: true,
				paging_length: 10,
				rows_counter: true,
				btn_reset: true,
			};
		setFilterGrid("list-table",filter_config);
	</script>
{% endblock %}

InstrumentDataManagement/templates/InstrumentDataManagement/viewInstrumentDetails.html
{% extends 'home/base.html' %}
{% load staticfiles%}
{% block body_block %}
	{% include 'InstrumentDataManagement/includes.html' %}
	{% include 'InstrumentDataManagement/addInstrumentSynynom.html' %}
	<h2>Instrument Details</h2>
	<div class="errorMessages">{{ errorMessages | default_if_none:"" }}</div>
	<table style="width: 30%;margin-left: auto;margin-right: auto;text-align:center">
		{% for synonym in instrumentSynonyms %}
		<tr>
			<th>{{ synonym.codification.name_c }}:</th>
			<td>{{ synonym.code_c }}</td>
			<td>
				<a href="{% url 'InstrumentDataManagement:deltInstrumentSynonym' synonym_id=synonym.id %}">
					<img src="{% static 'home/images/delete.png' %}"/>
				</a>
			</td>
		</tr>
		{% endfor%}
	</table>
	<hr>
	<table style="width: 30%;margin-left: auto;margin-right: auto;text-align:center">
		<tr>
			<th colspan=2>Name:</th>
			<td colspan=2>{{ instrument.name_c }}</td>
		</tr>
		<tr>
			<th>Market:</th>
			<td>{{ instrument.market }}</td>
			<th>Market data type:</th>
			<td>{{ instrument.marketdatatype }}</td>
		</tr>
		<tr>
			<th>Country:</th>
			<td>{{ instrument.country }}</td>
			<th>Main currency:</th>
			<td>{{ instrument.currency }}</td>
		</tr>
		<tr>
			<th>Risk country:</th>
			<td>{{ instrument.risk_country }}</td>
			<th>Underlying currency:</th>
			<td>{{ instrument.underlying_currency }}</td>
		</tr>
	</table>
	<br>
	<table style="width: 40%;margin-left: auto;margin-right: auto;text-align:center">
		<tr>
			<th>Multiplier</th>
			<th>Nominal</th>
			<th>Expiry date</th>
			<th>Contract Forward Rate</th>
			<th>Maturity</th>
			<th>BPV</th>
			<th>Strike</th>
		</tr>
		<tr>
			<td>{{ instrument.multiplier_n | default_if_none:""}}</td>
			<td>{{ instrument.nominal_n | default_if_none:""}}</td>
			<td>{{ instrument.expiry_d | default_if_none:""}}</td>
			<td>{{ instrument.contract_forward_rate_n | default_if_none:""}}</td>
			<td>{{ instrument.maturity_n | default_if_none:""}}</td>
			<tD>{{ instrument.bpv_n | default_if_none:""}}</td>
			<tD>{{ instrument.strike_n | default_if_none:""}}</td>
		</tr>
	</table>
	<hr/>
	<a href="{% url 'InstrumentDataManagement:viewInstrument' %}">Back</a> /
	<a href="#" onclick="overlayClick('instrument-synonym-overlay')">Add synonym</a> /
	<a href="{% url 'InstrumentDataManagement:deleteInstrument' instrument.id %}" class="confirmation">Delete instrument</a>
	
	
	<script type="text/javascript">
	    var elems = document.getElementsByClassName('confirmation');
	    var confirmIt = function (e) {
	        if (!confirm('Are you sure you want to delete this instrument and all its data?')) e.preventDefault();
	    };
	    for (var i = 0, l = elems.length; i < l; i++) {
	        elems[i].addEventListener('click', confirmIt, false);
	    }
	</script>

{% endblock %}