ManualUpload/urls.py
'''
Created on 25.11.2016

@author: Moustafa Shama
'''
from django.conf.urls import url

from . import views

app_name = 'ManualUpload'

urlpatterns = [
    url(r'^uploadData/$', views.uploadData, name='uploadData'),
]

MarketDataManagement/urls.py
'''
Created on 14.09.2016

@author: Moustafa Shama
'''
from django.conf.urls import url

from . import views

app_name = 'MarketDataManagement'

urlpatterns = [
    url(r'^viewMapping/$', views.manageMapping, name='manageMapping'),
    url(r'^viewMapping/(active)/$', views.manageMapping, name='manageMapping'),
    url(r'^deactivateMapping/$', views.changeMappingActivation, name='editMapping'),
    url(r'^deactivateMapping/(?P<mapping_id>[0-9]+)/$', views.changeMappingActivation, name='changeMappingActivation'),
    url(r'^updateData/$', views.updateData, name='updateData'),
    url(r'^updateData/?source=(DS|BBG)$', views.updateData, name='updateData'),
]

QuantServer/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('home.urls')),
    url(r'^InstrumentDataManagement/', include('InstrumentDataManagement.urls')),
    url(r'^MarketDataManagement/', include('MarketDataManagement.urls')),
    url(r'^RiskModelManagement/', include('RiskModelManagement.urls')),
    url(r'^PortfolioPositionManagement/', include('PortfolioPositionManagement.urls')),
    url(r'^RiskModelManagement/', include('RiskModelManagement.urls')),
    url(r'^UserManagement/', include('UserManagement.urls')),
    url(r'^ManualUpload/', include('ManualUpload.urls')),
    url(r'^Reporting/', include('Reporting.urls')),
]

Reporting/urls.py
'''
Created on 30.11.2016

@author: Moustafa Shama
'''
from django.conf.urls import url

from . import views

app_name = 'Reporting'

urlpatterns = [
    url(r'^QELV/$', views.mainCalculations_QELV, name='QELV'),
    url(r'^KINI/$', views.mainCalculations_KINI, name='KINI'),
]

RiskModelManagement/urls.py
'''
Created on 24.11.2016

@author: Moustafa Shama
'''
from django.conf.urls import url

from . import views

app_name = 'RiskModelManagement'

urlpatterns = [
    url(r'^viewRiskfactors/$', views.viewRiskfactors, name='viewRiskfactors'),
    url(r'^viewRiskfactor/$', views.viewRiskfactor, name='viewRiskfactor'),
    url(r'^viewRiskfactor/(?P<riskfactor_id>[0-9]+)/$', views.viewRiskfactor, name='viewRiskfactor'),
    url(r'^addRiskfactor/$', views.addRiskfactor, name='addRiskfactor'),
    url(r'^editComposition/(?P<riskfactor_id>[0-9]+)/$', views.editRiskfactorComposition, name='editRiskfactorComposition'),
    url(r'^editMapping/(?P<riskfactor_id>[0-9]+)/$', views.editRiskfactorMapping, name='editRiskfactorMapping'),
    url(r'^deleteMapping/(?P<mapping_id>[0-9]+)/$', views.deleteRiskfactorMapping, name='deleteRiskfactorMapping'),
    url(r'^editRiskfactor/(?P<riskfactor_id>[0-9]+)/$', views.editRiskfactor, name='editRiskfactor'),
      url(r'^deleteRiskfactor/(?P<riskfactor_id>[0-9]+)/$', views.deleteRiskfactor, name='deleteRiskfactor'),
#     url(r'^viewFunctions/$', views.viewFunctions, name='viewFunctions'),
#     url(r'^viewFunctions/(?P<function_id>[0-9]+)/$', views.viewFunctions, name='viewFunctions'),
#     url(r'^addFunction/$', views.addFunction, name='addFunction'),
]

home/urls.py
'''
Created on 22.06.2016

@author: Moustafa Shama
'''

from django.conf.urls import url

from . import views


app_name = 'home'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^checkLogin/$', views.checkLogin, name='checkLogin'),
]

home/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models

app_name = 'home'

home/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.forms.models import model_to_dict


from UserManagement.models import User

# Create your views here.
def index(request):
    if 'user' in request.session:
        loginStatus = True
    else:
        request.session.flush()
        loginStatus = False
    context = {
               'loginStatus': loginStatus,
               'homeText': 'This is Homepage',
               }
    return render(request, 'home/index.html', context)


def checkLogin(request):
    try:
        user = User.objects.get(windows_login_c = request.POST['uname'])
        request.session['user'] = model_to_dict(user)
        loginStatus = True
    except ObjectDoesNotExist:
        loginStatus = False
    context = {
               'loginStatus': loginStatus,
               }
    return render(request, 'home/index.html', context)

home/templates/home/base.html
<!DOCTYPE html>
<head>
	{% load staticfiles %}
	
	<link rel="stylesheet" type="text/css" href="{% static 'home/css/style.css' %}" />
	<link rel="shortcut icon" type="image/png" href="{% static 'home/images/favicon.ico' %}"/>
	<title>Quant Capital</title>
</head>

<body>
	<h3>
    	<img src="{% static 'home/images/qc_logo.png' %}" alt="Quant Capital Management" height="80px" width="300px"/>
	</h3>
	
	<table style="width:100%">
		<tr>
			<td style="width:10%;vertical-align:top;">
				<ul>
					<li><a class="active" href="{% url 'home:index' %}">Home</a></li>
					<li class="dropdown">
						<a href="#news">Reporting</a>
						<div class="dropdown-content">
							<ul class="dropdown-menu-list">
								<li class="dropdown-menu">
									<a href="#">Monthly Report</a>
									<div class="dropdown-submenu-content">
										<ul class="dropdown-submenu-list">
											<li><a href="{% url 'Reporting:QELV' %}">QELV</a></li>
											<li><a href="{% url 'Reporting:KINI' %}">KINI</a></li>
										</ul>
									</div>
								</li>
								<li class="dropdown-menu">
									<a href="#">Daily Report</a>
									<div class="dropdown-submenu-content">
										<ul class="dropdown-submenu-list">
											<li><a href="#">Report 1</a></li>
											<li><a href="#">Report 2</a></li>
										</ul>
									</div>
								</li>					
							</ul>
						</div>
					</li>
					<li class="dropdown">
						<a href="#">Instrument Management</a>
						<div class="dropdown-content">
							<ul class="dropdown-menu-list">
								<li class="dropdown-menu">
									<a href="{% url 'InstrumentDataManagement:newInstrument' %}">New instrument</a>						
								</li>
								<li class="dropdown-menu">
									<a href="{% url 'InstrumentDataManagement:viewInstrument' %}">View instruments</a>						
								</li>
								<li class="dropdown-menu">
									<a href="{% url 'InstrumentDataManagement:searchInstruments' %}">Search instruments</a>						
								</li>
								<li class="dropdown-menu">
									<a href="{% url 'InstrumentDataManagement:viewAssetClasses' %}">Asset classes</a>						
								</li>					
							</ul>
						</div>
					</li>
					<li class="dropdown">
						<a href="#">Market data Management</a>
						<div class="dropdown-content">
							<ul class="dropdown-menu-list">
								<li class="dropdown-menu">
									<a href="{% url 'MarketDataManagement:manageMapping' 'active' %}">View active mapping</a>						
								</li>
								<li class="dropdown-menu">
									<a href="{% url 'MarketDataManagement:manageMapping'%}">View all mapping</a>						
								</li>
								<li class="dropdown-menu">
									<a href="{% url 'MarketDataManagement:updateData'%}">Update data</a>						
								</li>
							</ul>
						</div>
					</li>
					<li class="dropdown">
						<a href="#">Portfolio/Position Management</a>
						<div class="dropdown-content">
							<ul class="dropdown-menu-list">
								<li class="dropdown-menu">
									<a href="{% url 'PortfolioPositionManagement:viewPortfolios' %}">View portfolios</a>						
								</li>
								<li class="dropdown-menu">
									<a href="{% url 'PortfolioPositionManagement:viewMandates' %}">View Mandates</a>						
								</li>
								<li class="dropdown-menu">
									<a href="{% url 'PortfolioPositionManagement:viewPositions' %}">View positions</a>						
								</li>
								<li class="dropdown-menu">
									<a href="{% url 'PortfolioPositionManagement:viewTransactions' %}">View transactions</a>						
								</li>
								<li class="dropdown-menu">
									<a href="{% url 'PortfolioPositionManagement:addTransactions' %}">Add transactions</a>						
								</li>
							</ul>
						</div>
					</li>
					<li class="dropdown">
						<a href="#">Risk Model Management</a>
						<div class="dropdown-content">
							<ul class="dropdown-menu-list">
								<li class="dropdown-menu">
									<a href="{% url 'RiskModelManagement:viewRiskfactors'%}">View risk factors</a>						
								</li>
								<li class="dropdown-menu">
									<a href="{% url 'RiskModelManagement:addRiskfactor'%}">Add risk factor</a>						
								</li>
							</ul>
						</div>
					</li>
					<li class="dropdown">
						<a href="#">User Management</a>
						<div class="dropdown-content">
							<ul class="dropdown-menu-list">
								<li class="dropdown-menu">
									<a href="#">View Users</a>						
								</li>
								<li class="dropdown-menu">
									<a href="#">View Functions</a>						
								</li>
								<li class="dropdown-menu">
									<a href="#">View Profiles</a>						
								</li>
							</ul>
						</div>
					</li>
					<li class="dropdown">
						<a href="#">Other</a>
						<div class="dropdown-content">
							<ul class="dropdown-menu-list">
								<li class="dropdown-menu">
									<a href="{% url 'ManualUpload:uploadData'%}">Upload data</a>						
								</li>
							</ul>
						</div>
					</li>
					<li><a href="#contact">Contact</a></li>
					<li><a href="#about">About</a></li>
				</ul>
			</td>
			<td style="width:90%;text-align: center;vertical-align:top;">
				{% block body_block %}
				{% endblock %}
			</td>
		</tr>
	</table>
</body>

home/templates/home/baseV2.html
<!DOCTYPE html>
<head>
	{% load staticfiles %}
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'home/css/navBarStyles.css' %}" />
	<link rel="shortcut icon" type="image/png" href="{% static 'home/images/favicon.ico' %}"/>
	<title>Quant Capital</title>
</head>

<body>

	<h3>
    	<img src="{% static 'home/images/qc_logo.png' %}" alt="Quant Capital Management" height="80px" width="300px"/>
	</h3>
	
	<div class="navbar navbar-default navbar-fixed-top" role="navigation">
		
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>            
            <div class="collapse navbar-collapse">
            	
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{% url 'home:index' %}">Home</a></li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Reporting<b class="caret"></b></a>

                        <ul class="dropdown-menu">
                            <li>
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Monthly report<b class="caret"></b></a>

                                <ul class="dropdown-menu">
                                    <li><a href="{% url 'Reporting:QELV' %}">QELV</a></li>
                                    <li><a href="{% url 'Reporting:KINI' %}">KINI</a></li>                                  
                                </ul>
                            </li>
                            <li>
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Daily report<b class="caret"></b></a>

                                <ul class="dropdown-menu">
                                    <li><a href="#">Test</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Instrument management <b class="caret"></b></a>

                        <ul class="dropdown-menu">
                            <li><a href="{% url 'InstrumentDataManagement:newInstrument' %}">New instrument</a></li>
                            <li><a href="{% url 'InstrumentDataManagement:viewInstrument' %}">View instruments</a></li>
                            <li><a href="{% url 'InstrumentDataManagement:searchInstruments' %}">Search instruments</a></li>
                            <li class="divider"></li>
                            <li><a href="{% url 'InstrumentDataManagement:viewAssetClasses' %}">Asset classes</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Market data management <b class="caret"></b></a>

                        <ul class="dropdown-menu">
                            <li><a href="{% url 'MarketDataManagement:manageMapping' 'active' %}">View active mapping</a></li>
                            <li><a href="{% url 'MarketDataManagement:manageMapping'%}">View all mapping</a></li>
                            <li><a href="{% url 'MarketDataManagement:updateData'%}">Update data</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Portfolio/Position management <b class="caret"></b></a>

                        <ul class="dropdown-menu">
                            <li><a href="{% url 'PortfolioPositionManagement:viewPortfolios' %}">View portfolios</a></li>
                            <li class="divider"></li>
                            <li><a href="{% url 'PortfolioPositionManagement:viewMandates' %}">View Mandates</a></li>
                            <li class="divider"></li>
                            <li><a href="{% url 'PortfolioPositionManagement:viewPositions' %}">View positions</a></li>
                            <li class="divider"></li>
                            <li><a href="{% url 'PortfolioPositionManagement:viewTransactions' %}">View transactions</a></li>
                            <li><a href="{% url 'PortfolioPositionManagement:addTransactions' %}">Add transactions</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Risk model management <b class="caret"></b></a>

                        <ul class="dropdown-menu">
                            <li><a href="{% url 'RiskModelManagement:viewRiskfactors'%}">View risk factors</a></li>
                            <li><a href="{% url 'RiskModelManagement:addRiskfactor'%}">Add risk factor</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">User management <b class="caret"></b></a>

                        <ul class="dropdown-menu">
                            <li><a href="#">View Users</a></li>
                            <li><a href="#">View Functions</a></li>
                            <li><a href="#">View Profiles</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Other <b class="caret"></b></a>

                        <ul class="dropdown-menu">
                            <li><a href="{% url 'ManualUpload:uploadData'%}">Upload data</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>

    <div class="container">

        <div class="navbar-template text-center">
            <table style="width:100%">
				<tr>
					<td style="width:90%;text-align: center;vertical-align:top;">
						{% block body_block %}
						{% endblock %}
					</td>
				</tr>
			</table>
        </div>

    </div>
    <script
	     src="https://code.jquery.com/jquery-3.1.1.js"
	     integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
	     crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<script type="text/javascript"  src="{% static 'home/js/navbar.js' %}"></script>
</body>

home/templates/home/index.html
{% extends 'home/base.html' %}

{% block body_block %}
	{% if not loginStatus %}
		<form id="user-login-form" action="{% url 'home:checkLogin' %}" method="POST">
			{% csrf_token %}
			<div>
				<h3><label> Login:</label></h3>
				<input type="text" name="uname" required><br>
				<input type="password" name="password" required><br><br>
			    <input type="submit" value="Confirm" class="submit-button"/>
			    <br />
			</div>
		</form>
	{% else %}
		<h2> this is the internal control center for Quant.</h2>
		<h2> Here you can call reports or manually trigger price data update and control instrument data</h2>
	{% endif %}
{% endblock %}