PortfolioPositionManagement/urls.py
'''
Created on 24.11.2016

@author: Moustafa Shama
'''
from django.conf.urls import url

from . import views

app_name = 'PortfolioPositionManagement'

urlpatterns = [
    url(r'^viewPortfolios/$', views.viewPortfolios, name='viewPortfolios'),
    url(r'^viewMandates/$', views.viewMandates, name='viewMandates'),
    url(r'^addMandate/$', views.addMandate, name='addMandate'),
    url(r'^viewPositions/$', views.viewPositions, name='viewPositions'),
    url(r'^editPosition/(?P<position_id>[0-9]+)/$', views.editPosition, name='editPosition'),
    url(r'^deletePosition/(?P<position_id>[0-9]+)/$', views.deletePosition, name='deletePosition'),
    url(r'^viewTransactions/$', views.viewTransactions, name='viewTransactions'),
    url(r'^editTransaction/(?P<transaction_id>[0-9]+)/$', views.editTransaction, name='editTransaction'),
    url(r'^deleteTransaction/(?P<transaction_id>[0-9]+)/$', views.deleteTransaction, name='deleteTransaction'),
    url(r'^addTransactions/$', views.addTransactions, name='addTransactions'),
]

QuantServer/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('home.urls')),
    url(r'^InstrumentDataManagement/', include('InstrumentDataManagement.urls')),
    url(r'^MarketDataManagement/', include('MarketDataManagement.urls')),
    url(r'^RiskModelManagement/', include('RiskModelManagement.urls')),
    url(r'^PortfolioPositionManagement/', include('PortfolioPositionManagement.urls')),
    url(r'^RiskModelManagement/', include('RiskModelManagement.urls')),
    url(r'^UserManagement/', include('UserManagement.urls')),
    url(r'^ManualUpload/', include('ManualUpload.urls')),
    url(r'^Reporting/', include('Reporting.urls')),
]

home/urls.py
'''
Created on 22.06.2016

@author: Moustafa Shama
'''

from django.conf.urls import url

from . import views


app_name = 'home'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^checkLogin/$', views.checkLogin, name='checkLogin'),
]

PortfolioPositionManagement/forms.py
'''
Created on 30.11.2016

@author: Moustafa Shama
'''

from django.utils.translation import ugettext_lazy as _

from django import forms

from PortfolioPositionManagement.models import Mandate, Position, Transaction,\
    Investment, Type, Status
from InstrumentDataManagement.models import Currency
from UserManagement.models import Group


class newMandateForm(forms.ModelForm):
    class Meta:
        model = Mandate
        fields = ('name_c',)
        labels = {
            'name_c': _('Name:'),
        }
        widgets = {
            'name_c': forms.TextInput(attrs={ 'required': 'true' }),
        }
        
class positionForm(forms.ModelForm):
    
    class Meta:
        model = Position
        
        fields = ('status', 'quantity_n', 'price_cost_n', 'price_valuation_kvg_n', 'currency',)
        
class newTransactionForm(forms.ModelForm):
    parent_investment = forms.ModelChoiceField(queryset=Investment.objects.exclude(portfolio__isnull=True), label='Parent Investment')
    investment = forms.ModelChoiceField(queryset=Investment.objects.exclude(instrument__isnull=True), label='Investment')
    type = forms.ModelChoiceField(queryset=Type.objects.all(), label='Type')
    status = forms.ModelChoiceField(queryset=Status.objects.all(), label='Status')
    quantity_n = forms.DecimalField(max_digits=30, decimal_places=10, label='Quantity')
    price_n = forms.DecimalField(max_digits=30, decimal_places=10, label='Price')
    currency = forms.ModelChoiceField(queryset=Currency.objects.all(), label='Currency')
    exchangerate_n = forms.DecimalField(max_digits=30, decimal_places=10, label='Exchange rate')
    tradedate_d = forms.DateField(widget=forms.TextInput(attrs=
                                {
                                    'type':'date',
                                    'class':'trade-date'
                                }))
    valuedate_d = forms.DateField(widget=forms.TextInput(attrs=
                                {
                                    'type':'date'
                                }))
    original_input_usergroup = forms.ModelChoiceField(queryset=Group.objects.all(), label='Currency')
    
    
    class Meta:
        model = Transaction
        fields = ('parent_investment', 'investment', 'type', 'status', 'quantity_n', 'price_n', 'currency', 'exchangerate_n', 'tradedate_d', 'valuedate_d', 'original_input_usergroup')
        
class editTransactionForm(forms.ModelForm):
    
    class Meta:
        model = Transaction
        
        fields = ('status', 'type', 'quantity_n', 'price_n', 'currency', 'exchangerate_n')

PortfolioPositionManagement/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse

from PortfolioPositionManagement.models import Portfolio, Mandate, Position,\
    Transaction
from UserManagement.models import User, Group

from datetime import datetime
from PortfolioPositionManagement.forms import newMandateForm, positionForm,\
    editTransactionForm, newTransactionForm
from django.forms.formsets import formset_factory

# Create your views here.

def viewMandates(request):
    if request.method == 'GET':
        mandates = Mandate.objects.all()
        mandateForm = newMandateForm()
        context = {
                   'mandates': mandates,
                   'mandateForm': mandateForm,
               }
        return render(request, 'PortfolioPositionManagement/viewMandates.html', context)
    
def addMandate(request):
    if request.method == 'POST':
        form = newMandateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('PortfolioPositionManagement:viewMandates')
        else:
            return HttpResponse('Error Saving Data')
        
def viewPositions(request):
    positions = Position.objects.all().order_by('investment__instrument__name_c')
    context = {
               'positions': positions,
               }
    return render(request, 'PortfolioPositionManagement/viewPositions.html', context)

def deletePosition(request, position_id=None):
    if position_id:
        position = Position.objects.get(pk=position_id)
        position.delete()
        
        return redirect('PortfolioPositionManagement:viewPositions')

def editPosition(request, position_id=None):
    if request.method == 'GET' and position_id:
        position = Position.objects.get(pk=position_id)
        editData = {
                    'status': position.status,
                    'quantity_n': position.quantity_n, 
                    'price_cost_n': position.price_cost_n, 
                    'price_valuation_kvg_n': position.price_valuation_kvg_n, 
                    'currency': position.currency,
                    }
        form = positionForm(editData)
        context = {
                   'position': position,
                   'editForm': form,
                   }
        return render(request, 'PortfolioPositionManagement/editPosition.html', context)
    if request.method == 'POST' and position_id:
        form = positionForm(request.POST)
        if form.is_valid():
            position = Position.objects.get(pk=position_id)
            
            position.status = form.cleaned_data['status']
            position.quantity_n = form.cleaned_data['quantity_n']
            position.price_cost_n = form.cleaned_data['price_cost_n']
            position.price_valuation_kvg_n = form.cleaned_data['price_valuation_kvg_n']
            position.currency = form.cleaned_data['currency']
            
            position.save()
            
            return redirect('PortfolioPositionManagement:viewPositions')
        else:
            position = Position.objects.get(pk=position_id)
            editData = {
                        'status': position.status,
                        'quantity_n': position.quantity_n, 
                        'price_cost_n': position.price_cost_n, 
                        'price_valuation_kvg_n': position.price_valuation_kvg_n, 
                        'currency': position.currency,
                        }
            form = positionForm(editData)
            errorMsg = 'there was an error'
            context = {
                       'position': position,
                       'editForm': form,
                       'errorMsg': errorMsg
                       }
            return render(request, 'PortfolioPositionManagement/editPosition.html', context)
    else:
        return redirect('PortfolioPositionManagement:viewPositions')

    
def viewTransactions(request):
    transactions = Transaction.objects.all()
    context = {
               'transactions': transactions,
               }
    return render(request, 'PortfolioPositionManagement/viewTransactions.html', context)

def addTransactions(request):
    TransactionFormSet = formset_factory(newTransactionForm, max_num=10, min_num=1)
    
    if request.method == 'GET':
        # prepare new transaction form
        transaction_formset = TransactionFormSet()
        context = {
                   'transaction_formset': transaction_formset,
                   }
        return render(request, 'PortfolioPositionManagement/addTransactions.html', context)
    if request.method == 'POST':
        # read form data
        transaction_formset = TransactionFormSet(request.POST, request.FILES)
        # check the validity of the transaction form
        if transaction_formset.is_valid():
            for form in transaction_formset.forms:
                # create new transaction
                transaction = form.save(commit=False)
                if request.session['user']:
                    transaction.create_user = request.session['user']
                transaction.createdate_d = datetime.now().date()
                transaction.save()                
            # update positions
            return redirect('PortfolioPositionManagement:viewTransactions')

def editTransaction(request, transaction_id=None):
    if request.method == 'GET' and transaction_id:
        transaction = Transaction.objects.get(pk=transaction_id)
        editData = {
                    'status': transaction.status,
                    'type': transaction.type, 
                    'quantity_n': transaction.quantity_n, 
                    'price_n': transaction.price_n, 
                    'exchangerate_n': transaction.exchangerate_n,
                    'currency': transaction.currency,
                    }
        form = editTransactionForm(editData)
        context = {
                   'transaction': transaction,
                   'editForm': form,
                   }
        return render(request, 'PortfolioPositionManagement/editTransaction.html', context)
    if request.method == 'POST' and transaction_id:
        form = editTransactionForm(request.POST)
        if form.is_valid():
            transaction = Transaction.objects.get(pk=transaction_id)
            
            transaction.status = form.cleaned_data['status']
            transaction.type = form.cleaned_data['type']
            transaction.quantity_n = form.cleaned_data['quantity_n']
            transaction.price_n = form.cleaned_data['price_n']
            transaction.exchangerate_n = form.cleaned_data['exchangerate_n']
            transaction.currency = form.cleaned_data['currency']
            
            transaction.save()
            
            return redirect('PortfolioPositionManagement:viewPositions')
        else:
            transaction = Transaction.objects.get(pk=transaction_id)
            editData = {
                    'status': transaction.status,
                    'type': transaction.type, 
                    'quantity_n': transaction.quantity_n, 
                    'price_n': transaction.price_n, 
                    'exchangerate_n': transaction.exchangerate_n,
                    'currency': transaction.currency,
                    }
            form = editTransactionForm(editData)
            errorMsg = 'there was an error'
            context = {
                       'transaction': transaction,
                       'editForm': form,
                       'errorMsg': errorMsg
                       }
            return render(request, 'PortfolioPositionManagement/editTransaction.html', context)
    else:
        return redirect('PortfolioPositionManagement:viewTransactions')

def deleteTransaction(request, transaction_id=None):
    if transaction_id:
        transaction = Transaction.objects.get(pk=transaction_id)
        transaction.delete()
        
        return redirect('PortfolioPositionManagement:viewTransactions')

def viewPortfolios(request):
    if request.method == 'GET':
        portfolios = Portfolio.objects.all()        
        context = {
                   'portfolios': portfolios,
                   }
        return render(request, 'PortfolioPositionManagement/viewPortfolios.html', context)
    elif request.method == 'POST' and request.is_ajax():
        changes =  request.POST.getlist('changes[]')
        message = ""
        for change in changes:
            change = change.split(',')
            try:
                portfolio = Portfolio.objects.get(pk=change[0])
                if(change[1] == 'true'):
                    portfolio.activeflag_b = True
                else:
                    portfolio.activeflag_b = False
                portfolio.last_modf_d = datetime.now().date()
                portfolio.last_modf_user = User(**request.session['user'])
                portfolio.save()
            except Exception as e:
                message = message + str(e)
        
        if len(message) == 0:
            message = "1"        

        return HttpResponse(message)
    elif request.method == 'POST' and not request.is_ajax():
        portfolios = Portfolio.objects.all()        
        context = {
                   'portfolios': portfolios,
                   }
        return render(request, 'PortfolioPositionManagement/viewPortfolios.html', context)

PortfolioPositionManagement/templates/PortfolioPositionManagement/addMandate.html
<div id="mandate-overlay" class="overlay-form">
	<div>
		<h3><label> Enter new mandate</label></h3>
		<form action="{% url 'PortfolioPositionManagement:addMandate'%}" method="POST">
		    {% csrf_token %}
		    {{ mandateForm.as_p }}
		    <br /> 
		    <input name="newMandate" type="submit" value="Submit" class="submit-button"/>
		</form>
	<a href='#' onclick='overlayClick("mandate-overlay")'>close</a>
	</div>
</div>

PortfolioPositionManagement/templates/PortfolioPositionManagement/addPortfolio.html
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Insert title here</title>
</head>
<body>

</body>
</html>

PortfolioPositionManagement/templates/PortfolioPositionManagement/addPosition.html
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Insert title here</title>
</head>
<body>

</body>
</html>

PortfolioPositionManagement/templates/PortfolioPositionManagement/addTransactions.html
{% extends 'home/base.html' %}
{% block body_block %}
	{% load staticfiles %}
	{% include 'PortfolioPositionManagement/includes.html' %}
	<script type="text/javascript"  src="{% static 'PortfolioPositionManagement/js/addTransaction.js' %}"></script>
	
	<form method="POST" action="{% url 'PortfolioPositionManagement:addTransactions' %}">
		{% csrf_token %}
		<table style="width: 90%;margin-left: auto;margin-right: auto;text-align:left; border-collapse: collapse;" border=1>
			<thead>
				<tr>
					<th>Parent Investment</th>
					<th>Investment</th>
					<th>Type</th>
					<th>Status</th>
					<th>Quantity</th>
					<th>Price</th>
					<th>Currency</th>
					<th>Exchange rate</th>
					<th>Trade date</th>
					<th>Value date</th>
					<th>Data source</th>
				</tr>
			</thead>
			<tbody>
			{{ transaction_formset.management_form }}
			{% for form in transaction_formset %}
				<tr class='transaction' id="{{ form.prefix }}">
				{% for field in form %}
				    <td>{{ field }}</td>
				{% endfor %}					
					<td>
						<a class="delete" href="#" style="text-decoration:none">
							<img src="{% static 'home/images/delete.png' %}"/>
						</a>
					</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
		<br><br>
		<a id="add" href="#" style="text-decoration:none">
			<img src="{% static 'home/images/add.png' %}"/>
		</a>
		<br><br>
		<input type="submit" value="Save transactions" class="submit-button"/>
	</form>
{% endblock %}

PortfolioPositionManagement/templates/PortfolioPositionManagement/editPosition.html
{% extends 'home/base.html' %}
{% block body_block %}
	{% include 'PortfolioPositionManagement/includes.html' %}
	
	Parent Investment: {{ position.parent_investment }} <br><br>
	Investment: {{ position.investment }} <br><br>
	
	<form method='POST' action="{% url 'PortfolioPositionManagement:editPosition' position.id %}" name='positionEditForm'>
		{% csrf_token %}
		
		{{ editForm.as_p }}
		
		<input name="editPosition" type="submit" value="Submit" class="submit-button"/>
	</form>

	
{% endblock %}

PortfolioPositionManagement/templates/PortfolioPositionManagement/editTransaction.html
{% extends 'home/base.html' %}
{% block body_block %}
	{% include 'PortfolioPositionManagement/includes.html' %}
	
	Parent Investment: {{ transaction.parent_investment }} <br><br>
	Investment: {{ transaction.investment }} <br><br>
	
	<form method='POST' action="{% url 'PortfolioPositionManagement:editTransaction' transaction.id %}" name='transactionEditForm'>
		{% csrf_token %}

		{{ editForm.as_p }}

		<input name="editPosition" type="submit" value="Save changes" class="submit-button"/>
	</form>

	
{% endblock %}

PortfolioPositionManagement/templates/PortfolioPositionManagement/includes.html
{% load staticfiles %}


<link rel="stylesheet" type="text/css" href="{% static 'PortfolioPositionManagement/css/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'home/css/filtergrid.css' %}" />


<script type="text/javascript"  src="{% static 'home/js/jquery.min.js' %}"></script>
<script type="text/javascript"  src="{% static 'home/js/moment.min.js' %}"></script>
<script type="text/javascript" src="{% static 'home/js/actb.js' %}"></script><!-- External script -->
<script type="text/javascript" src="{% static 'home/js/tablefilter.js' %}"></script> <!-- Credit: Max Guglielmi -->
<script type="text/javascript"  src="{% static 'PortfolioPositionManagement/js/scripts.js' %}"></script>

PortfolioPositionManagement/templates/PortfolioPositionManagement/viewMandates.html
{% extends 'home/base.html' %}
{% block body_block %}
	{% include 'PortfolioPositionManagement/includes.html' %}
	{% include 'PortfolioPositionManagement/addMandate.html' %}
	<div class='mandate-div-list'>
		<ul class='mandates-list'>		
			{% for mandate in mandates %}
			<li>
				{{ mandate.name_c }}
			</li>
			{% endfor %}
		</ul>
	</div>
	<br>
	<a href="#" onclick="overlayClick('mandate-overlay')" class='button-link'>New mandate</a>
{% endblock %}

PortfolioPositionManagement/templates/PortfolioPositionManagement/viewPortfolioDetails.html
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Insert title here</title>
</head>
<body>

</body>
</html>

PortfolioPositionManagement/templates/PortfolioPositionManagement/viewPortfolios.html
{% extends 'home/base.html' %}
{% block body_block %}
	<script language="javascript" type="text/javascript">
		var changedPortfolios = [];
	</script>
	{% include 'PortfolioPositionManagement/includes.html' %}
	<form id='portfolios-list-form' method='post' action="{% url 'PortfolioPositionManagement:viewPortfolios' %}">
		{% csrf_token %}
		<span id="message"></span>
		<table style="width: 90%;margin-left: auto;margin-right: auto;text-align:left">
			<tr>
				<th>Name</th>
				<th>Created by</th>
				<th>Created on</th>
				<th>Last modified by</th>
				<th>Last modified on</th>
				<th>Primary Risk model</th>
				<th>Is active</th>
			</tr>
			{% for portfolio in portfolios %}
			<tr>
				<td>{{ portfolio.name_c }}</td>
				<td>{{ portfolio.create_user.lastname_c | default_if_none:"" }}, {{ portfolio.create_user.firstname_c  | default_if_none:"" }}</td>
				<td>{{ portfolio.create_d | default_if_none:"" }}</td>
				<td>
					{% if portfolio.last_modf_user %}
						{{ portfolio.last_modf_user.lastname_c  | default_if_none:"" }}, {{ portfolio.last_modf_user.firstname_c  | default_if_none:"" }}
					{% endif %}
				</td>
				<td>{{ portfolio.last_modf_d | default_if_none:"" }}</td>
				<td>{{ portfolio.primary_riskmodel.name_c | default_if_none:"" }}</td>
				<td>
					<input 	type="checkbox" 
							name="is_active" 
							value="{{ portfolio.activeflag_b }}"
							onclick="updateChangedPortfolios({{ portfolio.id }}, $(this))"
							{% ifequal portfolio.activeflag_b True %}
							checked
							{% endifequal %}
					>
				</td>
			</tr>
			{% endfor %}
		</table>
		<br/>
		 <input type="submit" id='save-button' class="submit-button" value="Save Changes" disabled>
	</form>
	
	<script type="text/javascript">
		$("#portfolios-list-form").submit(function(event)
		{
			event.preventDefault();
			ajaxPost(event);
		});
	</script>
{% endblock %}

PortfolioPositionManagement/templates/PortfolioPositionManagement/viewPositions.html
{% extends 'home/base.html' %}
{% block body_block %}
	{% load staticfiles %}
	{% include 'PortfolioPositionManagement/includes.html' %}
	<table style="border-collapse: collapse; width: 90%;margin-left: auto;margin-right: auto;text-align:left" border=1 id="list-table">
		<tr>
			<th> </th>
			<th>Parent investment</th>
			<th>Investment</th>
			<th>Status</th>
			<th>From date</th>
			<th>To date</th>
			<th>Quantity</th>
			<th>Price cost</th>
			<th>Price valuation KVG</th>
			<th>Currency</th>
			<th>Exchange rate</th>
			<th>Original input user group</th>
			<th>Market value KVG EUR</th>
			<th>Market value KVG foreign currency</th>
			<th>Nominal value for bonds</th>
			
		</tr>
		{% for position in positions %}
		<tr>
			<td >
				<a href="{% url 'PortfolioPositionManagement:editPosition' position.id %}" style="text-decoration:none">
					<img src="{% static 'home/images/edit.png' %}"/>
				</a>
				|
				<a href="{% url 'PortfolioPositionManagement:deletePosition' position.id %}" style="text-decoration:none">
					<img src="{% static 'home/images/delete.png' %}"/>
				</a>
				
			</td>
			<td>{{ position.parent_investment }}</td>
			<td>{{ position.investment }}</td>
			<td>{{ position.status }}</td>
			<td>{{ position.positiondatefrom_d }}</td>
			<td>{{ position.positiondateto_d | default_if_none:"" }}</td>
			<td>{{ position.quantity_n }}</td>
			<td>{{ position.price_cost_n }}</td>
			<td>{{ position.price_valuation_kvg_n }}</td>
			<td>{{ position.currency }}</td>
			<td>{{ position.exchangerate_n }}</td>
			<td>{{ position.original_input_usergroup }}</td>
			<td>{{ position.market_value_kvg_eur_n | default_if_none:"" }}</td>
			<td>{{ position.market_value_kvg_fc_n | default_if_none:"" }}</td>
			<td>{{ position.nominal_value_bond_n | default_if_none:"" }}</td>
		</tr>
		{% endfor %}
	</table>
	
	<script language="javascript" type="text/javascript">
		var filter_config = 	{
				paging: true,
				paging_length: 100,
				rows_counter: true,
				btn_reset: true,
			};
		setFilterGrid("list-table",filter_config);
	</script>
{% endblock %}

PortfolioPositionManagement/templates/PortfolioPositionManagement/viewTransactions.html
{% extends 'home/base.html' %}
{% block body_block %}
	{% load staticfiles %}
	{% include 'PortfolioPositionManagement/includes.html' %}
	<table style="border-collapse: collapse; width: 90%;margin-left: auto;margin-right: auto;text-align:left" border=1 id="list-table">
		<tr>
			<th> </th>
			<th>Parent investment</th>
			<th>Investment</th>
			<th>Currency</th>
			<th>Status</th>
			<th>Type</th>
			<th>Quantity</th>
			<th>Price</th>
			<th>Exchangerate</th>
			<th>Volume EUR</th>
			<th>Volume Foreign Currency</th>
			<th>Trade Date</th>
			<th>Value Date</th>
			<th>Create Date</th>
			<th>Create User</th>
			<th>Nominal Value Bond</th>
			<th>Original input user group</th>
			
		</tr>
		{% for transaction in transactions %}
		<tr>
			<td >
				<a href="{% url 'PortfolioPositionManagement:editTransaction' transaction.id %}" style="text-decoration:none">
					<img src="{% static 'home/images/edit.png' %}"/>
				</a>
				|
				<a href="{% url 'PortfolioPositionManagement:deleteTransaction' transaction.id %}" style="text-decoration:none">
					<img src="{% static 'home/images/delete.png' %}"/>
				</a>
				
			</td>
			<td>{{ transaction.parent_investment }}</td>
			<td>{{ transaction.investment }}</td>
			<td>{{ transaction.currency }}</td>
			<td>{{ transaction.status }}</td>
			<td>{{ transaction.type }}</td>
			<td>{{ transaction.quantity_n }}</td>
			<td>{{ transaction.price_n }}</td>
			<td>{{ transaction.exchangerate_n }}</td>
			<td>{{ transaction.volumne_eur_n }}</td>
			<td>{{ transaction.volume_fc_n }}</td>
			<td>{{ transaction.tradedate_d }}</td>
			<td>{{ transaction.valuedate_d }}</td>
			<td>{{ transaction.createdate_d }}</td>
			<td>{{ transaction.create_user }}</td>
			<td>{{ transaction.nominal_value_bond_n | default_if_none:"" }}</td>
			<td>{{ transaction.original_input_usergroup }}</td>
		</tr>
		{% endfor %}
	</table>
	
	<script language="javascript" type="text/javascript">
		var filter_config = 	{
				paging: true,
				paging_length: 100,
				rows_counter: true,
				btn_reset: true,
			};
		setFilterGrid("list-table",filter_config);
	</script>
{% endblock %}