QuantServer/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('home.urls')),
    url(r'^InstrumentDataManagement/', include('InstrumentDataManagement.urls')),
    url(r'^MarketDataManagement/', include('MarketDataManagement.urls')),
    url(r'^RiskModelManagement/', include('RiskModelManagement.urls')),
    url(r'^PortfolioPositionManagement/', include('PortfolioPositionManagement.urls')),
    url(r'^RiskModelManagement/', include('RiskModelManagement.urls')),
    url(r'^UserManagement/', include('UserManagement.urls')),
    url(r'^ManualUpload/', include('ManualUpload.urls')),
    url(r'^Reporting/', include('Reporting.urls')),
]

RiskModelManagement/urls.py
'''
Created on 24.11.2016

@author: Moustafa Shama
'''
from django.conf.urls import url

from . import views

app_name = 'RiskModelManagement'

urlpatterns = [
    url(r'^viewRiskfactors/$', views.viewRiskfactors, name='viewRiskfactors'),
    url(r'^viewRiskfactor/$', views.viewRiskfactor, name='viewRiskfactor'),
    url(r'^viewRiskfactor/(?P<riskfactor_id>[0-9]+)/$', views.viewRiskfactor, name='viewRiskfactor'),
    url(r'^addRiskfactor/$', views.addRiskfactor, name='addRiskfactor'),
    url(r'^editComposition/(?P<riskfactor_id>[0-9]+)/$', views.editRiskfactorComposition, name='editRiskfactorComposition'),
    url(r'^editMapping/(?P<riskfactor_id>[0-9]+)/$', views.editRiskfactorMapping, name='editRiskfactorMapping'),
    url(r'^deleteMapping/(?P<mapping_id>[0-9]+)/$', views.deleteRiskfactorMapping, name='deleteRiskfactorMapping'),
    url(r'^editRiskfactor/(?P<riskfactor_id>[0-9]+)/$', views.editRiskfactor, name='editRiskfactor'),
      url(r'^deleteRiskfactor/(?P<riskfactor_id>[0-9]+)/$', views.deleteRiskfactor, name='deleteRiskfactor'),
#     url(r'^viewFunctions/$', views.viewFunctions, name='viewFunctions'),
#     url(r'^viewFunctions/(?P<function_id>[0-9]+)/$', views.viewFunctions, name='viewFunctions'),
#     url(r'^addFunction/$', views.addFunction, name='addFunction'),
]

home/urls.py
'''
Created on 22.06.2016

@author: Moustafa Shama
'''

from django.conf.urls import url

from . import views


app_name = 'home'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^checkLogin/$', views.checkLogin, name='checkLogin'),
]

RiskModelManagement/views.py
from django.shortcuts import render, redirect
from RiskModelManagement.models import Riskfactor, Riskfactor_Mapping,\
    RiskfactorComposition
from InstrumentDataManagement.models import Instrument, Marketdatatype
from PortfolioPositionManagement.models import Portfolio
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.


def viewRiskfactors(request):
    riskfactors = Riskfactor.objects.all()        
    context = {
               'riskfactors': riskfactors,
               }
    return render(request, 'RiskModelManagement/viewRiskfactors.html', context)
    
def editRiskfactorMapping(request, riskfactor_id=None):
    if request.method == 'POST':
        parent_riskfactor = Riskfactor.objects.get(pk=riskfactor_id)
        if "replaceMapping" in request.POST:
            current_mapping = Riskfactor_Mapping.objects.filter(riskfactor=parent_riskfactor)
            for mapping_element in current_mapping:
                mapping_element.delete()
                
        for instrument_id in request.POST.getlist('instrument_mapping_list[]'):
            reference_instrument = Instrument.objects.get(pk=instrument_id)
            portfolio = Portfolio.objects.get(pk=request.POST['portfolio'])
            Riskfactor_Mapping(
                               reference_instrument=reference_instrument,
                               riskfactor=parent_riskfactor,
                               portfolio=portfolio,
                               ).save()
    return redirect('RiskModelManagement:viewRiskfactor', riskfactor_id=riskfactor_id)

def editRiskfactorComposition(request, riskfactor_id=None):
    if request.method == 'POST':
        parent_riskfactor = Riskfactor.objects.get(pk=riskfactor_id)
        
        current_composition = RiskfactorComposition.objects.filter(parent_riskfactor=parent_riskfactor)
        for composition_element in current_composition:
            composition_element.delete()
                
        for component_riskfactor_id, weight in zip(request.POST.getlist('riskfactor[]'),request.POST.getlist('weight[]')):
            if component_riskfactor_id:
                component_riskfactor = Riskfactor.objects.get(pk=component_riskfactor_id)
                RiskfactorComposition(
                                      parent_riskfactor=parent_riskfactor,
                                      riskfactor=component_riskfactor,
                                      weight_n=weight,
                                      ).save()
    return redirect('RiskModelManagement:viewRiskfactor', riskfactor_id=riskfactor_id)

def editRiskfactor(request, riskfactor_id=None):
    if request.method == 'POST':
        
        parent_riskfactor = Riskfactor.objects.get(pk=riskfactor_id)
        hedge_instrument = Instrument.objects.get(pk=request.POST['riskfactorhedgeinstrument'])
        riskfactor_name = request.POST['riskfactor_name']
        if len(riskfactor_name) == 0:
            riskfactor_name = None
        
        parent_riskfactor.hedgeinstrument = hedge_instrument
        parent_riskfactor.name_c = riskfactor_name
        
        parent_riskfactor.save()
    return redirect('RiskModelManagement:viewRiskfactor', riskfactor_id=riskfactor_id)

def deleteRiskfactor(request, riskfactor_id=None):
    if riskfactor_id:
        riskfactor = Riskfactor.objects.get(pk=riskfactor_id)
        riskfactor.delete()
        
        return redirect('RiskModelManagement:viewRiskfactors')

def deleteRiskfactorMapping(request, mapping_id=None):
    riskfactormapping = Riskfactor_Mapping.objects.get(id=mapping_id)
    riskfactor = riskfactormapping.riskfactor
    riskfactormapping.delete()
    return redirect('RiskModelManagement:viewRiskfactor', riskfactor_id=riskfactor.id)
    
def viewRiskfactor(request, riskfactor_id=None):
    if request.method == 'POST' and 'riskfactorList' in request.POST:
        selectedRiskfactor = request.POST['riskfactorList']
        if 'deleteRiskfactor' in request.POST:
            return deleteRiskfactor(request, riskfactor_id=selectedRiskfactor)
    elif request.method == 'GET' and riskfactor_id:
        selectedRiskfactor = riskfactor_id
    else:
        return redirect('RiskModelManagement:viewRiskfactors')
    
    riskfactor = Riskfactor.objects.get(pk=selectedRiskfactor)
    try:
        riskfactor_mapping = Riskfactor_Mapping.objects.filter(riskfactor=riskfactor).order_by('reference_instrument__name_c')
    except ObjectDoesNotExist:
        riskfactor_mapping = None
        
    try:
        riskfactor_composition = RiskfactorComposition.objects.filter(parent_riskfactor=riskfactor)
    except ObjectDoesNotExist:
        riskfactor_composition = None
        
    hedge_instrument_list = Instrument.objects.filter(marketdatatype__type_c__in=['Derivative'])
    mapping_instrument_list = Instrument.objects.filter(marketdatatype__type_c__in=['Equity','Fixed_Income','Derivative']).order_by('name_c')
    index_list = Instrument.objects.filter(marketdatatype__type_c__in=['Index','Currency'])
    riskfactors = Riskfactor.objects.all()
    portfolios = Portfolio.objects.all()
    
    context = {                 
               'mapping_instrument_list': mapping_instrument_list,
               'hedge_instrument_list': hedge_instrument_list,
               'index_list': index_list,
               'riskfactors': riskfactors,
               'portfolios': portfolios,
               
               'riskfactor': riskfactor,
               'riskfactor_mapping': riskfactor_mapping,
               'riskfactor_composition': riskfactor_composition,
               }
    return render(request, 'RiskModelManagement/viewRiskfactor.html', context)

def addRiskfactor(request):
    if request.method == 'GET':
        hedge_instrument_list = Instrument.objects.filter(marketdatatype__type_c__in=['Derivative'])
        mapping_instrument_list = Instrument.objects.filter(marketdatatype__type_c__in=['Equity','Fixed_Income','Derivative']).order_by('name_c')
        index_list = Instrument.objects.filter(marketdatatype__type_c__in=['Index','Currency'])
        riskfactors = Riskfactor.objects.all()
        portfolios = Portfolio.objects.all()
        
        context = {
                   'mapping_instrument_list': mapping_instrument_list,
                   'hedge_instrument_list': hedge_instrument_list,
                   'index_list': index_list,
                   'riskfactors': riskfactors,
                   'portfolios': portfolios,
                }
        return render(request, 'RiskModelManagement/addRiskfactor.html', context)
    elif request.method == 'POST':
        riskfactor_name = request.POST['riskfactor_name']
        if len(riskfactor_name) == 0:
            riskfactor_name = None
        riskfactor_instrument = Instrument.objects.get(pk=request.POST['riskfactorinstrument']) 
        if request.POST['riskfactorhedgeinstrument']:
            hedge_instrument = Instrument.objects.get(pk=request.POST['riskfactorhedgeinstrument'])
        else:
            hedge_instrument = None
            
        parent_riskfactor = Riskfactor(name_c=riskfactor_name, riskfactorinstrument=riskfactor_instrument, hedgeinstrument=hedge_instrument)
        parent_riskfactor.save()
        
        if ('has_composition' in request.POST) and len(request.POST.getlist('riskfactor[]')) > 0:
            for riskfactor_id,weight in zip(request.POST.getlist('riskfactor[]'), request.POST.getlist('weight[]')):
                if riskfactor_id:
                    riskfactor_element = Riskfactor.objects.get(pk=riskfactor_id)
                    RiskfactorComposition(
                                          parent_riskfactor=parent_riskfactor,
                                          riskfactor=riskfactor_element,
                                          weight_n=weight,
                                          ).save()
        
        if ('has_mapping' in request.POST) and request.POST['instrument_mapping_list[]']:
            for instrument_id in request.POST.getlist('instrument_mapping_list[]'):
                reference_instrument = Instrument.objects.get(pk=instrument_id)
                portfolio = Portfolio.objects.get(pk=request.POST['mandate'])
                Riskfactor_Mapping(
                                   reference_instrument=reference_instrument,
                                   riskfactor=parent_riskfactor,
                                   portfolio=portfolio,
                                   ).save()
        
        successMessage = 'Risk factor is saved successfully'
        
        hedge_instrument_list = Instrument.objects.filter(marketdatatype__type_c__in=['Derivative'])
        mapping_instrument_list = Instrument.objects.filter(marketdatatype__type_c__in=['Equity','Fixed_Income','Derivative'])
        index_list = Instrument.objects.filter(marketdatatype__type_c__in=['Index','Currency'])
        riskfactors = Riskfactor.objects.all()
        portfolios = Portfolio.objects.all()
        
        context = { 
                   'successMessage': successMessage,                  
                   'mapping_instrument_list': mapping_instrument_list,
                   'hedge_instrument_list': hedge_instrument_list,
                   'index_list': index_list,
                   'riskfactors': riskfactors,
                   'mandates': mandates,
                }
        return render(request, 'RiskModelManagement/addRiskfactor.html', context)

RiskModelManagement/templates/RiskModelManagement/addRiskfactor.html
{% extends 'home/base.html' %}
{% block body_block %}
	{% load staticfiles %}
	{% include 'RiskModelManagement/includes.html' %}
	<script type="text/javascript"  src="{% static 'RiskModelManagement/js/addTransaction.js' %}"></script>
	{% if successMessage %}
		<div class="successMessages">{{ successMessage | default_if_none:"" }}</div>
	{% endif %}
	<form method='POST' id ='addRiskfactor-form' action="{% url 'RiskModelManagement:addRiskfactor'%}">
		{% csrf_token %}
		<div id='main-data'>
			<table>
				<tr>
					<th>
						Riskfactor name:
					</th>
					<td>
						<input name="riskfactor_name" type="text" value="">
					</td>
					<th>
						Choose corresponding index:
					</th>
					<td>
						<select name='riskfactorinstrument'>
							{% for index_instrument in index_list %}
							<option value="{{ index_instrument.id }}">{{ index_instrument.name_c }}</option>
							{% endfor %}
						</select>
					</td>
					<th>
						Choose hedge instrument:
					</th>
					<td>
						<select name='riskfactorhedgeinstrument'>
							<option value="" selected>---------</option>
							{% for instrument in hedge_instrument_list %}
							<option value="{{ instrument.id }}">{{ instrument.name_c }}</option>
							{% endfor %}
						</select>
					</td>
				</tr>
			</table>
		</div>
		<hr>
		<div id='composition-data'>
			<table id='riskfactor-composition-table'>
				<tr>
					<td colspan=4 style="text-align:right">
						<input 	type="checkbox" name="has_composition"> has composition
					</td>
				</tr>
				<tr id='composition-table-original-row'>
					<th style="text-align:left">
						Component risk factor:
					</th>
					<td style="text-align:left">
						<select name='riskfactor[]'>
							<option value="" selected>---------</option>
							{% for riskfactor in riskfactors %}
							<option value="{{ riskfactor.id }}">{{ riskfactor.riskfactorinstrument.name_c }}</option>
							{% endfor %}
						</select>
					</td>
					<th>
						Weight:
					</th>
					<td style="text-align:right">
						<input type="number" name="weight[]" step=".0001" max="9" min="0.0001">
					</td>
				</tr>
				<tr>
					<td colspan=4 style="text-align:right">
						<a href="#" onclick="addRow()">
							<img src="{% static 'home/images/add.png' %}"/>
						</a>
					</td>
				</tr>
			</table>
		</div>
		<hr>
		<div id='mapping-data'>
			<table>
				<tr>
					<td colspan=4 style="text-align:right">
						<input 	type="checkbox" name="has_mapping"> has mapping
					</td>
				</tr>
				<tr>
					<th style="text-align:left">
						Mapped instruments:
					</th>
					<td style="text-align:left">
						<select name="instrument_mapping_list[]" id="instrument_mapping_list" multiple size="15" style="width: 400px;overflow:auto">
					    {% for instrument in mapping_instrument_list %}
							<option value="{{ instrument.id }}">{{ instrument.name_c }}</option>
						{% endfor %}
						</select>
					</td>
				</tr>
				<tr>
					<th style="text-align:left">
						Choose portfolio
					</th>
					<td style="text-align:left">
						<select name='portfolio'>
							{% for portfolio in portfolios %}
							<option value="{{ portfolio.id }}">{{ portfolio.name_c }}</option>
							{% endfor %}
						</select>
					</td>
				</tr>
			</table>
			
		</div>
		<br>
		<input type='submit' name="addRiskfactor" value='Save risk factor'/>
	</form>
{% endblock %}

RiskModelManagement/templates/RiskModelManagement/editRiskfactor.html
<div id="edit-riskfactor-overlay" class="overlay-form-large">
	<div>
		<h3><label> Edit riskfactor</label></h3>
		<form action="{% url 'RiskModelManagement:editRiskfactor' riskfactor.id %}" method="POST">
		    {% csrf_token %}
		    <table>
		    	<tr>
		    		<th>Name:</th>
		    		<td>
		    			<input name="riskfactor_name" type="text" value="{{ riskfactor.name_c | default_if_none:"" }}">
		    		</td>
		    	</tr>
				<tr>					
					<th>
						Choose hedge instrument:
					</th>
					<td>
						<select name='riskfactorhedgeinstrument'>
							<option value="">---------</option>
							{% for instrument in hedge_instrument_list %}
								{% if instrument.id == riskfactor.hedgeinstrument.id %}
									<option value="{{ instrument.id }}" selected>{{ instrument.name_c }}</option>
								{% else %}
									<option value="{{ instrument.id }}">{{ instrument.name_c }}</option>
								{% endif %}
							{% endfor %}
						</select>
					</td>
				</tr>
			</table>
		    <br /> 
		    <input name="saveRiskfactor" type="submit" value="Save" class="submit-button"/>
		</form>
	<a href='#' onclick='overlayClick("edit-riskfactor-overlay")'>close</a>
	</div>
</div>

RiskModelManagement/templates/RiskModelManagement/editRiskfactorComposition.html
{% load staticfiles %}
{% load l10n %}
<div id="edit-composition-overlay" class="overlay-form-large">
	<div>
		<h3><label> Edit composition</label></h3>
		<form action="{% url 'RiskModelManagement:editRiskfactorComposition' riskfactor.id %}" method="POST">
		    {% csrf_token %}
		    <table id='riskfactor-composition-table-edit'>
		    {% if riskfactor_composition %}
			    {% for risk_element in riskfactor_composition %}
					<tr id="row{{ risk_element.id }}">
						<th style="text-align:left">
							Component risk factor:
						</th>
						<td style="text-align:left">
							<select name='riskfactor[]'>
								<option value="" selected>---------</option>
								{% for riskfactor in riskfactors %}
									{% if riskfactor.id == risk_element.riskfactor.id %}
										<option value="{{ riskfactor.id }}" selected>{{ riskfactor.riskfactorinstrument.name_c }}</option>
									{% else %}
										<option value="{{ riskfactor.id }}">{{ riskfactor.riskfactorinstrument.name_c }}</option>
									{% endif %}
								{% endfor %}
							</select>
						</td>
						<th>
							Weight:
						</th>
						<td style="text-align:right">
							{% localize off %}
							<input type="number" name="weight[]" step=".0001" max="9" min="0.0001" value="{{ risk_element.weight_n |stringformat:"f" }}">
							{% endlocalize %}
						</td>
						<td colspan=4 style="text-align:right">
							<a href="#" onclick="deleteRowEditTable('row{{ risk_element.id }}')">
								<img src="{% static 'home/images/delete.png' %}"/>
							</a>
						</td>
					</tr>
				{% endfor %}
			{% else %}
				<tr id="row1">
					<th style="text-align:left">
						Component risk factor:
					</th>
					<td style="text-align:left">
						<select name='riskfactor[]'>
							<option value="" selected>---------</option>
							{% for riskfactor in riskfactors %}
								<option value="{{ riskfactor.id }}">{{ riskfactor.riskfactorinstrument.name_c }}</option>							
							{% endfor %}
						</select>
					</td>
					<th>
						Weight:
					</th>
					<td style="text-align:right">
						{% localize off %}
						<input type="number" name="weight[]" step=".0001" max="9" min="0.0001">
						{% endlocalize %}
					</td>
					<td colspan=4 style="text-align:right">
						<a href="#" onclick="deleteRowEditTable('row1')">
							<img src="{% static 'home/images/delete.png' %}"/>
						</a>
					</td>
				</tr>
			{% endif %}
				<tr>
					<td colspan=4 style="text-align:right">
						<a href="#" onclick="addRowEditTable()">
							<img src="{% static 'home/images/add.png' %}"/>
						</a>
					</td>
				</tr>
			</table>
		    <br /> 
		    <input name="saveComposition" type="submit" value="Save" class="submit-button"/>
		</form>
	<a href='#' onclick='overlayClick("edit-composition-overlay")'>close</a>
	</div>
</div>

RiskModelManagement/templates/RiskModelManagement/editRiskfactorMapping.html
<div id="edit-mapping-overlay" class="overlay-form-large">
	<div>
		<h3><label> Edit mapping</label></h3>
		<form action="{% url 'RiskModelManagement:editRiskfactorMapping' riskfactor.id %}" method="POST">
		    {% csrf_token %}
		    <input type="checkbox" name="replaceMapping" value="False" title="If checked current mapping will be replaced"> Replace current mapping
		    <table>
				<tr>
					<th style="text-align:left">
						Mapped instruments:
					</th>
					<td style="text-align:left">
						<select name="instrument_mapping_list[]" id="instrument_mapping_list" multiple size="15" style="width: 300px;overflow:auto">
					    {% for instrument in mapping_instrument_list %}
							<option value="{{ instrument.id }}">{{ instrument.name_c }}</option>
						{% endfor %}
						</select>
					</td>
				</tr>
				<tr>
					<th style="text-align:left">
						Choose Portfolio
					</th>
					<td style="text-align:left">
						<select name='portfolio'>
							{% for portfolio in portfolios %}
							<option value="{{ portfolio.id }}">{{ portfolio.name_c }}</option>
							{% endfor %}
						</select>
					</td>
				</tr>
			</table>
		    <br /> 
		    <input name="saveMapping" type="submit" value="Save" class="submit-button"/>
		</form>
	<a href='#' onclick='overlayClick("edit-mapping-overlay")'>close</a>
	</div>
</div>

RiskModelManagement/templates/RiskModelManagement/includes.html
{% load staticfiles %}


<link rel="stylesheet" type="text/css" href="{% static 'RiskModelManagement/css/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'home/css/filtergrid.css' %}" />


<script type="text/javascript"  src="{% static 'home/js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'home/js/actb.js' %}"></script><!-- External script -->
<script type="text/javascript" src="{% static 'home/js/tablefilter.js' %}"></script> <!-- Credit: Max Guglielmi -->
<script type="text/javascript"  src="{% static 'RiskModelManagement/js/scripts.js' %}"></script>

RiskModelManagement/templates/RiskModelManagement/viewRiskfactor.html
{% extends 'home/base.html' %}
{% block body_block %}
	{% load staticfiles %}
	{% include 'RiskModelManagement/includes.html' %}
	{% include 'RiskModelManagement/editRiskfactorMapping.html' %}
	{% include 'RiskModelManagement/editRiskfactorComposition.html' %}
	{% include 'RiskModelManagement/editRiskfactor.html' %}
	<div id='main-data'>
		<table>
			<tr>
				<th style="text-align:left">
					Riskfactor:
				</th>
				<td style="text-align:left">
					{{ riskfactor.name_c | default_if_none:"" }}
				</td>
				<th>
					Riskfactor index:
				</th>
				<td style="text-align:center">
					{{ riskfactor.riskfactorinstrument }}
				</td>
				<th style="text-align:right">
					Hedge instrument:
				</th>
				<td style="text-align:right">
					{{ riskfactor.hedgeinstrument | default_if_none:"" }}
				</td>
				<td style="text-align:right">
					<a href="#" onclick="overlayClick('edit-riskfactor-overlay')">
						<img src="{% static 'home/images/edit.png' %}"/>
					</a>
				</td>
			</tr>
		</table>
	</div>
	<hr>
	<div id='composition-data'>
		<table id='riskfactor-composition-table'>
			<tr>
				<th style="text-align:left">Riskfactor component</th>
				<th style="text-align:right">Weight</th>
				<td style="text-align:right">
					<a href="#" onclick="overlayClick('edit-composition-overlay')">
						<img src="{% static 'home/images/edit.png' %}"/>
					</a>
				</td>				
			</tr>
		{% for risk_element in riskfactor_composition %}
			<tr>
				<td style="text-align:left">
					{{ risk_element.riskfactor.riskfactorinstrument }}
				</td>
				<td style="text-align:right">
					{{ risk_element.weight_n }}
				</td>
			</tr>
		{% endfor %}
		</table>
	</div>
	<hr>
	<div id='mapping-data'>
		<table>
			<tr>
				<th style="text-align:left">Portfolio</th>
				<th style="text-align:right">Instrument</th>
				<td style="text-align:right">
					<a href="#" onclick="overlayClick('edit-mapping-overlay')">
						<img src="{% static 'home/images/edit.png' %}"/>
					</a>
				</td>
			</tr>
		{% for mapping_element in riskfactor_mapping %}
			<tr>
				<td style="text-align:left">
					{{ mapping_element.portfolio }}
				</td>
				<td style="text-align:right">
					{{ mapping_element.reference_instrument }}
				</td>
				<td colspan=4 style="text-align:right">
					<a href="{% url 'RiskModelManagement:deleteRiskfactorMapping' mapping_element.id %}">
						<img src="{% static 'home/images/delete.png' %}"/>
					</a>
				</td>
			</tr>
		{% endfor %}
		</table>
		
	</div>
{% endblock %}

RiskModelManagement/templates/RiskModelManagement/viewRiskfactors.html
{% extends 'home/base.html' %}
{% block body_block %}
{% include 'RiskModelManagement/includes.html' %}
<form method='POST' id ='chooseRiskfactor-form' action="{% url 'RiskModelManagement:viewRiskfactor'%}">
	{% csrf_token %}
	Sort by:
	<select name="sortBy" id="sortBy" onchange="sortRiskfactors()">
	   <option value="id">ID</option>
	   <option value="name">Name</option>
	</select>
	<br><br>
	<select name="riskfactorList" id="riskfactorList" size="20" style="width: 600px;overflow:auto">
    {% for riskfactor in riskfactors %}
		<option value="{{ riskfactor.id }}">{{ riskfactor.name_c | default_if_none:riskfactor.riskfactorinstrument }}</option>
	{% endfor %}
	</select>
	<br><br>
	<input type='submit' name="showRiskfactorDetails" value='Show riskfactor details'/>
	<a class='button-link' href="{% url 'RiskModelManagement:addRiskfactor'%}">Add new riskfactor</a>
	<input type='submit' name="deleteRiskfactor" value='Delete Riskfactor'/>
</form>
{% endblock %}